### ISSUE TITLE
Using notebook : a error of measure_sine_pref() when running gcal model in the notebook

### ISSUE THREAD

**Issue by wenqi2015** [ioam/topographica#623]
In [31]:
from topo.command.analysis import measure_sine_pref
measure_sine_pref()['V1']['OrientationPreference'].top
100% measurement progress 00:00:12
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-31-89a47b17a2e8> in <module>()
      1 from topo.command.analysis import measure_sine_pref
----> 2 measure_sine_pref()['V1']['OrientationPreference'].top

/home/wenqi/env/topographica/external/holoviews/holoviews/core/layout.pyc in __getitem__(self, key)
    465                 raise KeyError('Index %s is outside available item range' % str(key))
    466             key = keys[idx]
--> 467         return super(Layout, self).__getitem__(key)
    468 
    469 

/home/wenqi/env/topographica/external/holoviews/holoviews/core/tree.pyc in __getitem__(self, identifier)
    169                 return self.__dict__[identifier]
    170             else:
--> 171                 raise KeyError(identifier)
    172         path_item = self
    173         for identifier in split_label:

KeyError: 'V1'

**Comment by wenqi2015** [comment]
Also, I can't find the class of measure_sine_pref defined in the "analysis.py" of the file"command"of the
file"topo". Why, please ?

**Comment by wenqi2015** [comment]
I suppose measure_sine_pref has been removed from the topo.command.analysis, but measure_or_pref could be imported from topo.command.analysis even I don't see it is defined
there. I am confused by this.

**Comment by jbednar** [comment]
measure_sine_pref and measure_or_pref can be imported from featuremapper.command; they are part of the FeatureMapper project, no longer Topographica itself.  If that's not enough to fix the problem above, please provide more context so that we can see what you are doing.  In particular, please separate the measure_sine_pref call from indexing it with ["V1"], showing what's being returned by measure_sine_sine pref before trying to index it.

**Comment by wenqi2015** [comment]
Thanks for answering. 
Version of topographica :  installed in April 28th ,2015
Running : the "gcal.ipynb" file in the notebook
Error : 
appeared when I run the last command in this page,
In [ ]:
from topo.command.analysis import measure_sine_pref
measure_sine_pref()['V1']['OrientationPreference'].top

just the same as showed above

**Comment by wenqi2015** [comment]
In addition, I can from topo.command.analysis import measure_sine_pref and measure_or_pref in the notebook, even I can not find they are defined in the "analysis.py" of the file"command"of the file"topo".
I am confused by this.

**Comment by philippjfr** [comment]
Which gcal.ipynb are you running? Have a look at the [GCAL Tutorial](http://ioam.github.io/media/topo/GCAL_Tutorial.html) and [GCAL Collector](http://ioam.github.io/media/topo/GCAL_Tutorial.html) notebooks. Those HTML snapshots are slightly outdated (I'll be updating them later today/tomorrow), but the latest and working ipynb files are available [here](https://github.com/ioam/topographica/tree/master/doc/Tutorials) or in topographica/doc/Tutorials if you have a local copy of the git repository. The return type for ``measure_sine_pref`` has changed in more recent versions of ``topographica`` and ``featuremapper``. This import:

```python
from topo.command.analysis import measure_sine_pref
```

is simply a legacy alias, to allow importing of the measurement commands. They have since moved to [ioam/featuremapper](https://github.com/ioam/featuremapper). All the measurement commands now return a [holoviews](ioam.github.com/holoviews) [Layout](http://ioam.github.io/holoviews/Tutorials/Containers#Layout), which displays all the measured preferences and selectivities:

```python
preferences = measure_sine_pref()
preferences.display('all')
```

and allows attribute access of the individual measurements, e.g.:

```python
preferences.OrientationPreference.V1
```

**Comment by wenqi2015** [comment]
I just test the"GCAL_Tutorial.ipynb" in topographica/doc/Tutorials, there are still some commands which
cannot be run. I don't think it is because my version of Topographica which is using git to install in about  5 days ago.

**Comment by jbednar** [comment]
Topographica is under very active development at the moment, but unfortunately we have not recently made a public release.  If you use the previous release 0.9.8, it should work, but it will be missing many features, and the code involved has changed so much since then that it's hard for us to recommend that you use that.  Unfortunately, the latest git code changes every day right now, and has been getting out of sync with the changes to the underlying libraries it is based on (primarily HoloViews, and to some extent FeatureMapper and ImaGen).  Thus if Philipp mentions that something should work, he's referring to the latest git version, not something 5 days ago.  You should do a "git pull" and try again, just before reporting any problems, because that way we will know it's a current problem.  As it is, you probably got a copy of Topographica from a period when we were working on HoloViews and breaking some things in Topographica, and before we fixed Topographica to match the changes. Sorry it's hard to keep up right now!

**Comment by wenqi2015** [comment]
Thank you and philippjfr very much! With your reminds, I installed the newer version and indeed, the
tutorials work well except 2 tiny errors I found and solved. Anyway, I should say sorry for reporting errors without doing the last step. Also, thanks for sharing so fantastic Topographica with us !

**Comment by jbednar** [comment]
No problem; glad it's useful!
