### ISSUE TITLE
what is the value of parameter" area" in the gcal script to produce the paper?

### ISSUE THREAD

**Issue by windform2015** [ioam/topographica#626]
I am confused by the value of "area" in the GCAL model. In the GCAL model script, it is 1.0 , but in the notebook tutorial "stevens_jn13.ipynb" which is in the directory topographica/models/stevens.jn13/, is
1.5. I would like to know, which is the value used to reproduce the stevens. et al(2013) paper ? Thanks.

**Comment by jbednar** [comment]
In most of our work, the value is 1.0, and I believe that all of the plots show a 1.0x1.0 area in the JN13 paper.  However, GCAL (like any laterally connected model with non-periodic boundary conditions) will have border effects near the edges of the cortical sheet, which can affect the density of pinwheels in those areas.  To avoid such issues, for the JN13 paper we increased the area to 1.5x1.5 for simulation, then cut off all but the central 1.0x1.0 region.

So, if you want to reproduce the paper exactly, you need to do 1.5x1.5, but we usually just use 1.0x1.0 ourselves and accept that there will be some effects of the border on the local details of the map shape.

**Comment by windform2015** [comment]
Thanks for your quick and nice answer. I am also wandering ,changing area=1.5 to area=1.0, pinwheel densities generated will be changed a little or not ?

**Comment by jbednar** [comment]
I'm not sure how significant the changes will be; any individual run is variable and we'd have to run the same number of runs as in jn13 if we wanted compare rigorously, and we haven't done that recently (though maybe Jean-Luc still remembers).  In any case the network should work the same; the number of pinweels is important just for making detailed comparisons with experimental data.

**Comment by jlstevens** [comment]
Using area 1.0 definitely distorts the pinwheel density due to easily visible edge effects. To get a good estimate of the pinwheel density for the models, we had to lots of runs (and then average the pinwheel density across them) as well as simulate area 1.5 before cropping to unit area. So in short, I can confirm Jim's response! :-)

As the the magnitude of the effect, I'm afraid I can't remember exactly so anything I say may be wrong. I am fairly sure the pinwheel density went *up* due to edge effects so at a very rough guess, I would say you might expect a pinwheel density of around 3.5 or so if you simulate GCAL with area 1.0 and take enough samples.

**Comment by windform2015** [comment]
Interesting! I would like to see how the pinwheel density changes and test the expectation. Thanks !
