### ISSUE TITLE
Saving and loading snapshots .

### ISSUE THREAD

**Issue by Hima-Mehta** [ioam/topographica#652]
Hi ,
Is it possible to take a snapshot and reload it in another .ty file with few new sheets  connecting to sheets  of that snapshot  ? 
Simply to ignore unnecessary running of partially working part every time ! 
PS : I have tried this already . does not give any syntax  error ! so If that affects logically then It would help.

**Comment by jbednar** [comment]
Sure.  A .ty file is just Python code (the special extension is just so that Windows will launch Topographica's Python on it rather than any other Python that might be installed), so you can do anything Python allows.  E.g. you can write a new .ty file that starts out with `load_snapshot("file.typ")`, and then add whatever commands you like to add additional sheets, etc.

**Comment by Hima-Mehta** [comment]
Thank you .
