### ISSUE TITLE
Are orientation maps measured by taking the effects of lateral interactions in V1 into account ?

### ISSUE THREAD

**Issue by windform2015** [ioam/topographica#657]
Hi, in the paper, Stevens et al.(2013), J.Neurosci, there is a statement saying: "To ensure consistent map measurement across all conditions, orientation maps in Figures 3–9 are measured before lateral interactions and the V1 activation function take affect (i.e., on the afferent input activity only)." I just want to see how maps are if the V1 interaction effects are taken into account in the measurement, but I am not sure these commands work for it:
"   topo.sim.run()  
    measure_or_pref()
    pref = topo.sim.V1.views.maps.OrientationPreference.last.data
    selec = topo.sim.V1.views.maps.OrientationSelectivity.last.data
......"
How could we check that ?

**Comment by jbednar** [comment]
Whether lateral interactions are included in map measurements is determined by the featuremapper.FeatureResponses.durations parameter, which defaults to [1.0] indicating that lateral interactions *are* included (though it can be overridden by subclasses or when the command is called).  The duration was reduced for the JN'13 paper, because an afferent-only measurement can reveal maps for non-robust models like the L model in that paper, but GCAL is robust and thus works well either way.

**Comment by windform2015** [comment]
Thank you so much !

**Comment by windform2015** [comment]
Sorry, you mean GCAL is robust for generating "very similar "orientation preference maps with or without lateral interactions in V1 ? If it is this case, it would suggest that neuron interactions in V1 are not important for orientation map formation and maturation. This suggestion seems to be a little controversial.

**Comment by jbednar** [comment]
Just to clarify, here I'm talking only about final, organized networks.  Obviously, lateral interactions are crucial for the formation and maturation of the map.  At iteration 0, the initial and settled responses will look extremely different, as will the maps made just from afferent weights (which will look like random noise) and those made including lateral interactions (which will be smoothly organized due to settling, but not selective).  But once the network is organized, the afferent and lateral weights are in a steady state where the initial afferent response and the final settled response are very similar.  That's because the afferent and lateral weights all learn by Hebbian learning, so they all match whatever the final activity pattern is after settling (on average).  At that point, whether you include lateral interactions or not for measuring maps is mostly irrelevant, though of course there will always be some small differences.

**Comment by windform2015** [comment]
Okay, now I understand it well, thanks a lot !
