### ISSUE TITLE
How to collect the data of unit responses for "measure_or_tuning_fullfield"?

### ISSUE THREAD

**Issue by windform2015** [ioam/topographica#658]
Hi, I want to calculate orientation selectivity index then I need to collect the data of responses by neuron
units to different orientation gratings, so I think I need to use  the class  "measure_or_tuning_fullfield" 
belonged to featuremapper.command. I run the syntax "measure_or_tuning_fullfield()" and get a movie
about the orientation tuning of units in the full field for various contrasts, but I am struggling for : how to get the data for that  ? I tried some ways but haven't work it out. Could you help give a hint, please ?

**Comment by jbednar** [comment]
If you're running any command in the notebook and get a figure displayed by HoloViews, you just need to type the same thing but add `.data` to the end if you want the data.  E.g. if you do `tunings = measure_or_tuning_fullfield()` then typing `tunings` will get you a visualization of some sort, and `tunings.data` will give you whatever is inside.  If you're looking at an element x, x.data will be the underlying data; otherwise it will be some sort of container that you can then look inside to find the data (indexed by various dimensions).  The HoloViews tutorials at holoviews.org explain how to navigate these data structures...

**Comment by windform2015** [comment]
Hi, thanks for your reply. Yes, before you answered it in  #658 , just I still didn't figure it out since I didn't
realize I need to look at the data structures instructed by holoviews.org. Sorry for asking the same question twice !
