### ISSUE TITLE
Sequential patterns using pattern.selector

### ISSUE THREAD

**Issue by Hima-Mehta** [ioam/topographica#661]
Hello ,
Is it possible to present patterns(images) sequentially from list of generators using pattern.selector() ? I am looking for direction preferences for a particular set of frames which were originally videos having objects moving in some direction.

**Comment by jbednar** [comment]
Anything like that is definitely possible, but I'm not sure precisely what you need.  It *sounds* like a case where I would set Selector.index to numbergen.ScaledTime(factor=1.0), so that whenever the time increases by 1, the index goes up by 1.

But for computing direction preferences, I'd normally use FeatureMapper to coordinate all this, not a Selector.

**Comment by Hima-Mehta** [comment]
Okey That was helpful ! Thank you
