### ISSUE TITLE
How are the connection fields for units near boarders of sheets created?

### ISSUE THREAD

**Issue by dancehours** [ioam/topographica#674]

**Comment by jbednar** [comment]
For better or for worse, I have been able to forget the details of all of those methods, so I'm afraid I can't help much with those specific questions.  But maybe it would be a good idea to outline what you are trying to do, because I wouldn't expect that any of those methods would need to be changed unless you are setting up something very unusual.

**Comment by dancehours** [comment]
I just want to remove the boundary effect for the connection fields and roll the matrix of input sheet so that
the units near the boundary and in central area have the same way to construct the connection fields.

**Comment by jbednar** [comment]
Ah, ok.  See the discussion in https://github.com/ioam/topographica/issues/566 . I'm sure that periodic boundary conditions would give orientation maps that look as good or better than the current ones, but I don't think that the simulations would be physically meaningful except under some very particular conditions that probably don't apply to animals.  So you're on your own with that investigation; good luck!

**Comment by dancehours** [comment]
Thanks a lot!
