### ISSUE TITLE
the mathematical form of elongated Gaussian pattern

### ISSUE THREAD

**Issue by kalok87** [ioam/topographica#682]
Dear developers,

Which of the following mathematical forms is used for Gaussian pattern performed in Retina?

1) 1/(2*Pi) * Exp[-(x^2 + y^2/a^2)]
2) 1/(2*Pi*a) * Exp[-(x^2 + y^2/a^2)]

where the a is the aspect ratio, and Sigma = 1 for simplification. Compare to the first one, the second expression above also normalize the y-component in the Gaussian pattern which leaves a in the denominator.

**Comment by jbednar** [comment]
This is a question about ImaGen, not Topographica per se, but both of these projects are open source, so you can and should check the code yourself whenever you have questions like that:

https://github.com/ioam/imagen/blob/master/imagen/patternfn.py#L39

https://github.com/ioam/imagen/blob/master/imagen/__init__.py#L75

**Comment by kalok87** [comment]
Dear Prof. Bednar. Thank you for your replying. I thought the packages are in the topo/pattern directory due to the .ty (from topo.pattern import gaussian) file but I cannot find it so I ask it here. Thank you for the help.

**Comment by jbednar** [comment]
Yes, that's confusing; topo.patterns was where the patterns were originally, but we split them out into the separate ImaGen project so that they could be reused in other contexts.  We kept the alias `topo.pattern` so that old code would keep working, but it's confusing that the code isn't really there!
