### ISSUE TITLE
from snapshot to output the parameters used in simulation

### ISSUE THREAD

**Issue by dancehours** [ioam/topographica#685]
Dear Bednar,

if I load a snapshot saved before, for example,GCAL model running 20000 times, is there a way
to know the parameters I used in that simulation ? e.g. the size of area I used.

**Comment by jbednar** [comment]
After loading it back in, you can try saving the "script_repr" of the simulation in memory, which will write out a Python text file showing how the objects can be recreated.  topo.sim.script_repr(), I think?

**Comment by dancehours** [comment]
Yes,it shows all the parameters of the simulation.Thanks !

**Comment by dancehours** [comment]
After I load a snapshot, could I continue running the model by using a different parameter, e.g. learning rate ?  Before it is 0.1 and now I change it to 0.2 to test.

**Comment by jbednar** [comment]
Some parameters only take effect during initialization, such as any of the size parameters for a CFProjection; there is no meaning to changing those after the weights have been initialized and where practical we try to mark those values constant so that you get a useful error message if you try.  But most other parameters, including all learning rates, thresholds, and similar parameters apply to every iteration, and can thus be changed whenever you like.
