### ISSUE TITLE
the values of orientation selectivity data are normalized or not ?

### ISSUE THREAD

**Issue by dancehours** [ioam/topographica#686]
Hello Bednar,
 by using the weighted average method, the orientation selectivity values for the measurement
"measure_or_pref()" can be larger than 1 for some units and these make me confuse, because I check the code for calculating selectivity that the vector_sum is divided by the sum of response values and this should give smaller values than 1.

**Comment by jbednar** [comment]
They are normalized and thus have a maximum value of 1.0, but because the selectivity is used in HSV plots to modulate the brightness, the selectivity is multiplied by a scaling factor before it is stored (`selectivity_multiplier`).  Ideally, this scaling factor would be applied only on plots, not on the underlying numerical values, but for whatever reason that's not how the code was originally implemented a couple of decades ago, and we've never wanted to break things by changing it later. 

See https://github.com/ioam/featuremapper/blob/master/featuremapper/__init__.py#L463 and https://github.com/ioam/featuremapper/blob/master/featuremapper/__init__.py#L531

**Comment by dancehours** [comment]
If the selectivity_multiplier use 17, does this mean the actual selectivity is small, around 0.1 ?

**Comment by jbednar** [comment]
Depends on a lot of factors.  Yes, usually, but you can make the selectivity be whatever you like, by adjusting the thresholds -- if you make it respond to only a very small range of orientations, then it will get a very high selectivity.  By default, the thresholds aren't even used, because they tend to have such a large impact that's unrelated to the actual preferences of the neurons.  Selectivity is a nebulous and slippery concept, and only really meaningful as a comparison between multiple neurons under similar conditions.
